import { motion } from 'motion/react'
import { ArrowUpRight } from 'lucide-react'
import PrCommentCard from '../ui/PrCommentCard'

const ease = [.16, 1, .3, 1] as const
const repositoryUrl = 'https://github.com/dr4ken-soul/Meridian'

/** Renders the split-screen hero. */
export default function Hero() { return <section id="top" className="min-h-[100dvh] grid grid-cols-1 lg:grid-cols-[0.85fr_1fr] bg-[var(--bg-primary)] relative overflow-hidden"><div className="flex flex-col justify-center px-6 md:px-12 lg:px-16 py-32 lg:py-20 relative z-[var(--z-content)]"><motion.h1 initial={{ opacity:0, filter:'blur(8px)', y:20 }} whileInView={{ opacity:1, filter:'blur(0px)', y:0 }} viewport={{ once:false, amount:.1 }} transition={{ duration:.6, ease, delay:.1 }} className="font-display text-4xl md:text-5xl lg:text-6xl font-semibold leading-[0.95] tracking-[-1.5px] max-w-[14ch]">Replay every prompt change against what already worked.</motion.h1><motion.p initial={{ opacity:0, filter:'blur(8px)', y:20 }} whileInView={{ opacity:1, filter:'blur(0px)', y:0 }} viewport={{ once:false, amount:.1 }} transition={{ duration:.6, ease, delay:.25 }} className="text-base md:text-lg text-[var(--text-secondary)] leading-relaxed mt-6 max-w-[42ch]">Meridian stores golden traces from your live agent, replays them on every prompt push, and posts the verdict straight to the pull request.</motion.p><motion.div initial={{ opacity:0, filter:'blur(8px)', y:20 }} whileInView={{ opacity:1, filter:'blur(0px)', y:0 }} viewport={{ once:false, amount:.1 }} transition={{ duration:.6, ease, delay:.4 }} className="mt-8 flex items-center gap-4"><a href={repositoryUrl} className="group bg-[var(--accent)] text-[var(--bg-primary)] text-sm font-medium pl-5 pr-1.5 py-1.5 rounded-[var(--radius-pill)] flex items-center gap-3 hover:bg-[var(--accent-hover)] transition-colors">Install Meridian <span className="w-7 h-7 rounded-full bg-black/10 flex items-center justify-center"><ArrowUpRight size={14} className="group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" /></span></a><a href={repositoryUrl} className="text-[var(--text-secondary)] text-sm font-medium hover:text-[var(--text-primary)] transition-colors">View on GitHub</a></motion.div></div><motion.div initial={{ opacity:0, filter:'blur(10px)', scale:.97 }} animate={{ opacity:1, filter:'blur(0px)', scale:1 }} transition={{ duration:.8, ease, delay:.3 }} className="relative flex items-center justify-center px-6 md:px-12 py-20 lg:py-0 bg-[var(--bg-secondary)] border-l border-[color:var(--border-subtle)] z-[var(--z-content)]"><PrCommentCard /></motion.div></section> }
